// HANDLES SEARCH QUERIES AND THE LOADING OF RESULTS
export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY'
export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS'
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS'
export const HIDE_SEARCH_RESULTS = 'HIDE_SEARCH_RESULTS'
export const REVEAL_SEARCH_RESULTS = 'REVEAL_SEARCH_RESULTS'

// HANDLES REQUESTS FOR ALL UNITS
export const ALL_UNITS_REQUEST = 'ALL_UNITS_REQUEST'
export const ALL_UNITS_SUCCESS = 'ALL_UNITS_SUCCESS'
export const ALL_UNITS_FAILURE = 'ALL_UNITS_FAILURE'

// HANDLES REQUESTS FOR INDIVIDUAL UNITS
export const UPDATE_CURRENT_UNIT = 'UPDATE_CURRENT_UNIT'
export const LOAD_PREVIOUS_UNIT = 'LOAD_PREVIOUS_UNIT'
export const CLEAR_CURRENT_UNIT = 'CLEAR_CURRENT_UNIT'
export const UNIT_DETAILS_REQUEST = 'UNIT_DETAILS_REQUEST'
export const UNIT_DETAILS_SUCCESS = 'UNIT_DETAILS_SUCCESS'
export const UNIT_DETAILS_FAILURE = 'UNIT_DETAILS_FAILURE'